apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app-k8s
spec:
  selector:
    matchLabels:
      app: food-app-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: food-app-k8s
    spec:
      containers:
        - name: food-app-k8s
          image: jafethadet/food-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080